name: example
description: Exemplo de como utilizar o package brasil_fields.
author: Rubens de Melo <rubensdemelo@gmail.com>
homepage: https://github.com/rubensdemelo/brasil_fields
version: 0.0.3

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  brasil_fields:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
