name: testes

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.1
      - uses: subosito/flutter-action@v1.3.2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test
