name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image:  google/dart:latest
    
    steps:
    - uses: actions/checkout@v1
    - run: git clone https://github.com/flutter/flutter.git
    - run: export PATH="$PATH:`pwd`/flutter/bin"
    - run: echo $PATH
    - run: flutter pub get
    - run: flutter test
