name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image:  google/dart:latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      with:
        flutter-version: '1.7.8+hotfix.4'
      run: flutter pub get
    - name: Run tests
      run: pub run test
