name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image:  google/dart:latest
    
    steps:
    - uses: actions/checkout@v1
    - run: cd ..
    - run: git clone https://github.com/flutter/flutter.git
    - run: ls
    - run: cd flutter
    - run: export PATH="$PATH:`pwd`/bin"
    - run: cd ..
    - run: echo $PATH
    - run: flutter doctor
    - run: cd brasil_fields
    - run: flutter doctor
    - run: flutter pub get
    - run: flutter test
