name: testes

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze --fatal-warnings
      - run: flutter test
