name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image:  google/dart:latest
    
    steps:
    - uses: actions/checkout@v1
    - name: flutter install dependencies
      run: flutter pub get
    - name: flutter run tests
      run: flutter run test
